#spring.application.name=Cypher-server-side
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
#spring.security.oauth2.resourceserver.opaquetoken.client-secret=bEn2xiAnG0mU2TERITERI0YOu5HzH0hE1CwJ1GOnG1tOnG6kAifAwAnchEnG

server:
  port: 8080
spring:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080
          opaque token:
            client-secret: bEn2xiAnG0mU2TERITERI0YOu5HzH0hE1CwJ1GOnG1tOnG6kAifAwAnchEnG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cypher?useSSL=false
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 50000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????

mybatis-plus:
  type-aliases-package: com.example.cypherserverside.entity.dto
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null